compat: fixup recent change to genlmsg_multicast_allns__no_has_4_params.path
error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

Fixes: 195893ea8e5 ("compat: fix unprotected genlmsg_multicast_allns")