compat: tests: rename unplug_fn to be unique
This test failed on some distros because:

    error: 'unplug_fn' redeclared as different kind of symbol

This (coincidentally) does not change the result, because the distribution
in question does not have this feature anyways, but try to be clean and avoid
this naming conflict.